### ISSUE TITLE
App crashes when I open trending page

### ISSUE THREAD

**Issue by ecuber** [lucyzhang04/326Project#138]
While testing PR #136, found that the trending page has potential to crash the application. It happened when I clicked the submit button, although I'm not sure which call directly led to a call to the longest-streak endpoint.

This is the error message that I received when I clicked the submit button:

```
Reached user contribution total endpoint
Executing (default): SELECT count(*) AS 'count' FROM 'Submissions' AS 'Submission' WHERE 'Submission' 'user_name' = 'ecubing' ;
Reached longest-streak endpoint.
/Users/elijah/Documents/GitHub/326Project/backend/controller/SubmissionController.js:100
const longestStreak = await this.model.getLongestStreak);
TypeError: this.model.getLongestStreak is not a function
at SubmissionController.getLongestStreak (/Users/elijah/Documents/GitHub/326Project/backend/controller/SubmissionController.js:100:44)
at /Users/elijah/Documents/GitHub/326Project/backend/routes/trending-routes.js:39:14
at Layer.handle [as handle_request] (/Users/elijah/Documents/GitHub/326Project/backend/node_modules/express/lib/router/layer.js:95:5)
at next (/Users/elijah/Documents/GitHub/326Project/backend/node_modules/express/lib/router/route.js:149:13)
at Route dispatch (/Users/elijah/Documents/GitHub/326Project/backend/node_modules/express/lib/router/route.js:119:3)
at Layer. handie lashande_requestsers eligal Documents ith Progetendemoles express contes cayer.gs: 95:5)
at /Users/elijah/Documents/GitHub/326Project/backend/node_modules/express/lib/router/index.js:284:15
at Function. process_params (/Users/elijah/Documents/GitHub/326Project/backend/node_modules/express/lib/router/index.js:346:12)
at next (/Users/elijah/Documents/GitHub/326Project/backend/node_modules/express/lib/router/index.js:280:10)
at Function.handle (/Users/elijah/Documents/GitHub/326Project/backend/node_modules/express/lib/router/index.js:175:3)
Node.js v23.3.0
```

**Comment by ecuber** [comment]
fixed in 7f1718

**Comment by cynthiaraj501** [comment]
Thank you for being very detailed. Glad the issue was resolved.
